// server/controllers/emailController.js
import { sendEmail } from '../utils/emails.js';

export const emailResume = async (req, res) => {
  try {
    const { email, targetRole, correctedResume, score, atsScore, strengths } = req.body;

    if (!email || !correctedResume) {
      return res.status(400).json({ success: false, message: 'Email and resume content are required.' });
    }

    const emailHtml = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #333; line-height: 1.6;">
        <div style="background-color: #f0fdf4; padding: 20px; border-radius: 12px; border-left: 5px solid #16a34a;">
          <h2 style="color: #15803d; margin-top: 0;">✨ Your Optimized Resume is Ready!</h2>
          <p style="margin: 5px 0; font-size: 16px;">Target Role: <strong>${targetRole}</strong></p>
          <p style="margin: 5px 0;">Overall Score: <strong>${score}/100</strong></p>
          <p style="margin: 5px 0;">ATS Score: <strong>${atsScore}/100</strong></p>
        </div>

        ${strengths && strengths.length > 0 ? `
          <h3 style="color: #444; margin-top: 20px;">🔑 Top Strengths</h3>
          <ul style="color: #555;">
            ${strengths.map(s => `<li style="margin-bottom: 5px;">${s}</li>`).join('')}
          </ul>
        ` : ''}

        <hr style="border: 0; border-top: 1px solid #eee; margin: 25px 0;" />

        <h3 style="color: #444;">📄 Optimized Resume Content</h3>
        <pre style="white-space: pre-wrap; font-family: inherit; font-size: 14px; color: #555; background: #f9fafb; padding: 15px; border-radius: 8px;">${correctedResume}</pre>
        
        <div style="margin-top: 30px; text-align: center; color: #999; font-size: 12px;">
          Generated by Shortlisted AI • Keep optimizing! 🚀
        </div>
      </div>
    `;

    await sendEmail(email, `✨ Your Optimized Resume for ${targetRole}`, emailHtml);

    res.json({ success: true, message: 'Resume sent successfully!' });
  } catch (error) {
    console.error('Email error:', error);
    res.status(500).json({ success: false, message: 'Failed to send email.' });
  }
};