// server/utils/generateATSReportPDF.js
import PDFDocument from 'pdfkit';

export const generateATSReportPDF = (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];
    
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfData = Buffer.concat(buffers);
      resolve(pdfData);
    });
    doc.on('error', reject);

    // 🎨 Header: Branding
    doc.rect(0, 0, doc.page.width, 100).fill('#16a34a'); // green-600
    doc.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold').text('Shortlisted AI', 50, 30);
    doc.fontSize(14).font('Helvetica').text('ATS Compatibility Report', 50, 60);
    doc.fontSize(10).text(`Generated: ${new Date().toLocaleDateString()}`, 50, 80);

    // 👤 User & Role Info
    doc.fillColor('#333333').fontSize(12).font('Helvetica-Bold').text('Candidate Information', 50, 130);
    doc.font('Helvetica').fontSize(10)
      .text(`Target Role: ${data.targetRole}`, 50, 145)
      .text(`Overall Score: ${data.score}/100`, 50, 160)
      .text(`ATS Score: ${data.atsCheck?.overallScore || 0}/100`, 50, 175);

    // 📊 ATS Score Bar
    const atsScore = data.atsCheck?.overallScore || 0;
    doc.rect(50, 190, 300, 20).strokeColor('#ccc').fill('#f3f4f6').fillAndStroke();
    doc.rect(50, 190, (atsScore * 3), 20).fill(atsScore >= 80 ? '#16a34a' : atsScore >= 50 ? '#f59e0b' : '#ef4444').fillAndStroke();
    doc.fillColor('#333').fontSize(9).text(`${atsScore}%`, 360, 195);

    // 🔑 Keyword Match Section
    doc.fontSize(12).font('Helvetica-Bold').text('Keyword Analysis', 50, 230);
    const keywords = data.atsCheck?.keywordMatch || {};
    
    doc.fontSize(10).font('Helvetica')
      .text('✅ Matched Keywords:', 50, 250)
      .fontSize(9)
      .text((keywords.matchedKeywords || []).slice(0, 10).join(', '), 50, 265, { width: 450 });
    
    doc.fontSize(10).font('Helvetica-Bold').text('⚠️ Missing Keywords:', 50, 295)
      .fontSize(9)
      .text((keywords.missingKeywords || []).slice(0, 10).join(', '), 50, 310, { width: 450 });

    // 📐 Formatting Checklist
    doc.fontSize(12).font('Helvetica-Bold').text('Formatting Compliance', 50, 345);
    const formatting = data.atsCheck?.formatting || {};
    
    const checks = [
      { label: 'No tables or text boxes', pass: !formatting.hasTables },
      { label: 'No images/graphics', pass: !formatting.hasGraphics },
      { label: 'Single-column layout', pass: !formatting.hasColumns },
      { label: 'Standard section headings', pass: formatting.usesStandardHeadings },
      { label: 'ATS-friendly fonts', pass: formatting.fontCompatibility !== 'Poor' },
    ];

    let yPos = 365;
    checks.forEach(check => {
      doc.fontSize(10)
        .fillColor(check.pass ? '#16a34a' : '#ef4444')
        .text(check.pass ? '✅' : '❌', 50, yPos)
        .fillColor('#333')
        .text(check.label, 70, yPos, { width: 400 })
        .text(check.pass ? 'Pass' : 'Fix Needed', 480, yPos, { align: 'right' });
      yPos += 18;
    });

    // 💡 Recommendations
    if (data.atsCheck?.recommendations?.length > 0) {
      doc.addPage();
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#333').text('Recommendations', 50, 50);
      doc.fontSize(10).font('Helvetica');
      
      data.atsCheck.recommendations.forEach((rec, i) => {
        doc.text(`${i + 1}. ${rec}`, 50, 70 + (i * 20), { width: 450, lineGap: 5 });
      });
    }

    // 🗺️ Roadmap Summary
    if (data.roadmap?.length > 0) {
      doc.addPage();
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#333').text('90-Day Growth Roadmap', 50, 50);
      doc.fontSize(10).font('Helvetica');
      
      data.roadmap.slice(0, 5).forEach((step, i) => {
        doc.font('Helvetica-Bold').text(`${i + 1}. ${step.skill}`, 50, 70 + (i * 40));
        doc.font('Helvetica').fontSize(9).text(step.actionStep, 50, 85 + (i * 40), { width: 450 });
        doc.fontSize(8).text(`⏱️ ${step.timeEstimate} • Priority: ${step.priority}`, 50, 100 + (i * 40));
      });
    }

    // 🦶 Footer
    doc.addPage();
    doc.fontSize(9).fillColor('#666').text(
      'Generated by Shortlisted AI • This report is for personal use only • Keep optimizing! 🚀',
      50, doc.page.height - 50, { align: 'center', width: doc.page.width - 100 }
    );

    doc.end();
  });
};